cart/urls.py
from django.conf.urls import url, include
from cart import views


urlpatterns = [
    url(r'^$', views.CartDetailView.as_view(), name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAddView.as_view(), name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemoveView.as_view(), name='cart_remove'),
    url(r'^coupons/', include('coupons.urls', namespace='coupons')),
]

eshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shop.urls', namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
]

orders/urls.py
from django.conf.urls import url
from orders import views


urlpatterns = [
    url(r'^create/$', views.OrderCreateForm.as_view(), name='order_create'),
]

shop/urls.py
from django.conf.urls import url
from shop import views


urlpatterns = [
    url(r'^$', views.ProductListView.as_view(),
        name='product_list'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.ProductDetailView.as_view(),
        name='product_detail'),
    url(r'^slug/(?P<slug>[-\w]+)/$',
        views.ProductListView.as_view(),
        name='product_list_by_category'),
]

cart/models.py
# from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import TemplateView
from django.views.generic.base import View
from django.views.generic.edit import FormView

from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from shop.recommender import Recommender


class CartAddView(FormView):
    form_class = CartAddProductForm

    def form_valid(self, form):
        cart = Cart(self.request)
        product_id = self.kwargs.get("product_id")
        product = get_object_or_404(Product, id=product_id)

        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
        return redirect('cart:cart_detail')


class CartRemoveView(View):

    def get(self, request, *args, **kwargs):
        cart = Cart(request)
        product_id = self.kwargs.get("product_id")
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        if cart:
            return redirect('cart:cart_detail')
        return redirect('/')


class CartDetailView(TemplateView):
    template_name = 'cart/detail.html'

    def get(self, request, **kwargs):
        cart = Cart(request)
        if len(cart) == 0:
            return redirect('/')
        context = self.get_context_data()
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(CartDetailView, self).get_context_data(**kwargs)
        cart = Cart(self.request)
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                initial={'quantity': item['quantity'],
                         'update': True})
        context['cart'] = cart
        context['coupon_apply_form'] = CouponApplyForm()
        r = Recommender()
        cart_products = [item['product'] for item in cart]
        context['recommended_products'] = r.suggest_products_for(cart_products, 4)

        return context

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %}{{ product.image.url}}{% else %}{% static "img/no_image.png" %}{% endif %}">
                            </a>
                        </td>
                        <td>{{ product.name }}</td>

                        <td>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Update">
                            {% csrf_token %}
                            </form>
                        </td>
                        <td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
                        <td class="num">${{ item.price }}</td>
                        <td class="num">${{ item.total_price }}</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            {% if cart.coupon %}
                <tr class="subtotal">
                    <td>Subtotal</td>
                    <td colspan="4"></td>
                    <td class="num">${{ cart.get_total_price }}</td>
                </tr>
                <tr>
                    <td>
                        "{{ cart.coupon.code }}" coupon
                        ({{ cart.coupon.discount }}% off)
                    </td>
                    <td colspan="4"></td>
                    <td class="num neg">
                        - ${{ cart.get_discount|floatformat:"2" }}
                    </td>
                </tr>
            {% endif %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td class="num">${{ cart.get_total_price_discount|floatformat:"2" }}</td>
            </tr>
        </tbody>
    </table>

    {% if recommended_products %}
        <div class="recommendations cart">
            <h3>People who bought this also bought</h3>
            {% for p in recommended_products %}
            <div class="item">
                <a href="{{ p.get_absolute_url }}">
                    <img src="
                            {% if p.image %}
                                {{ p.image.url }}
                            {% else %}
                                {% static "img/no_image.png" %}
                            {% endif %}"
                         alt="Item Image">
                </a>
                <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
            </div>
            {% endfor %}
        </div>
    {% endif %}

    <p>Apply a coupon: </p>
    <form action="{% url "cart:coupons:apply" %}" method="post">
        {{  coupon_apply_form }}
        <input type="submit" value="Apply">
        {%  csrf_token %}
    </form>
    <p class="text-right">
      <a href="{% url "shop:product_list" %}" class="button light">Continue shopping</a>
      <a href="{% url "orders:order_create" %}" class="button">
        Checkout
      </a>
    </p>
{% endblock %}